// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA85QAKTFLujKGVWrdTWrjafQYi0z1R3eY',
    appId: '1:108674270513:web:804b73f80b60079b261c10',
    messagingSenderId: '108674270513',
    projectId: 'rackity-17b5f',
    authDomain: 'rackity-17b5f.firebaseapp.com',
    storageBucket: 'rackity-17b5f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoi3wuc2vzmKx5rTGui7OD3qW2Kqt7ZtQ',
    appId: '1:108674270513:android:3230b52ce7d7ea10261c10',
    messagingSenderId: '108674270513',
    projectId: 'rackity-17b5f',
    storageBucket: 'rackity-17b5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3PEfTYTfvErxT9v3zUH504Ghup3kTrIs',
    appId: '1:108674270513:ios:1188a8dd59718fce261c10',
    messagingSenderId: '108674270513',
    projectId: 'rackity-17b5f',
    storageBucket: 'rackity-17b5f.appspot.com',
    iosClientId: '108674270513-vvu3i1leakde7vsn5d47iaar3bp07jdi.apps.googleusercontent.com',
    iosBundleId: 'com.example.rackity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3PEfTYTfvErxT9v3zUH504Ghup3kTrIs',
    appId: '1:108674270513:ios:1188a8dd59718fce261c10',
    messagingSenderId: '108674270513',
    projectId: 'rackity-17b5f',
    storageBucket: 'rackity-17b5f.appspot.com',
    iosClientId: '108674270513-vvu3i1leakde7vsn5d47iaar3bp07jdi.apps.googleusercontent.com',
    iosBundleId: 'com.example.rackity',
  );
}
